language: cpp
compiler: gcc
before_install:
    # libstdc++-4.8-dev
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    # clang++-3.2 and gcc 4.8
    - sudo add-apt-repository --yes ppa:h-rayflood/llvm
    # bullet
    - sudo apt-add-repository --yes ppa:openrave/release
    - sudo apt-get -qq update
    # Playdeb has bullet in their repo
    - wget http://archive.getdeb.net/install_deb/playdeb_0.3-1~getdeb1_all.deb
    - sudo dpkg -i playdeb_0.3-1~getdeb1_all.deb
    # No ppa for GLFW3 at this time. Compiling by hand!
    - sudo apt-get -qq install xorg-dev libglu1-mesa-dev
    - git clone --depth=100 https://github.com/glfw/glfw.git
    - cd glfw
    # GLFW requests cmake-2.8.9 but travis runs 2.8.7, we use the last commit using 2.8.7
    - git checkout 96d230becb0c612b3f3631cb6cf83ebe0a393b71
    - CMAKE_CXX_FLAGS=-fPIC CMAKE_C_FLAGS=-fPIC cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:bool=true .
    - sudo make install
    - cd ..
    - wget https://rapidjson.googlecode.com/files/rapidjson-0.11.zip
    - unzip rapidjson-0.11.zip -d /tmp
    - sudo cp -r /tmp/rapidjson/include /usr
    - sudo apt-get install lua5.1-dev
    - wget https://bitbucket.org/alexames/luawrapper/downloads/luawrapper.zip
    - unzip luawrapper.zip -d /tmp
    - sudo cp -r /tmp/luawrapper /usr
    # Download GLM 9.5 from github
    - wget https://github.com/g-truc/glm/archive/0.9.5.3.zip 
    - unzip 0.9.5.3.zip -d /tmp
    - sudo cp -r /tmp/glm-0.9.5.3/glm /usr/include
install:
    # Install libstdv++ 4.8 and clang
    - sudo apt-get -qq install libstdc++-4.8-dev clang-3.3
    # Setup clang and gcc
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    # GLEW
    - sudo apt-get -q -y install libglew-dev
    # Raknet
    - git submodule update --init --depth=1 raknet
    - cd raknet
    - sudo cmake CMakeLists.txt
    - sudo make
    - cd ..
    # OpenAL, Vorbis and OGG
    - sudo apt-get -q -y install libogg-dev libvorbis-dev libopenal-dev libalure-dev
    # Bullet
    - sudo apt-get -q -y install libbullet-dev
    # install and build gtest
    - sudo apt-get -q -y install libgtest-dev
    - BUILD_PATH=$(pwd)
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - GTEST_ROOT=/usr/src/gtest
    - export GTEST_ROOT
    - cd $BUILD_PATH
#    - sudo apt-get -y install automake libtool cmake
before_script:
    - mkdir build
    - mv assets build
    - cd build
    - cmake -DTCC_BUILD_TESTS=True ..
script:
    - make
    - mv assets bin
    - cd bin
    - ./TCCTests

notifications:
    #email:
        #- my.mail@bar.com
    # I can also set up Glitch to output build results as well if we don't want the travis bot join/part spam
    irc:
        - "chat.freenode.net#project-trillek"
